apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: orderflow-flink
  namespace: data-pipeline
spec:
  image: ghcr.io/w1024ji/orderflow-flink-job:93156fa0e62460a1ec687f8b7a9451a6051847aa
  flinkVersion: v1_18
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "2"
    state.checkpoints.dir: file:///tmp/checkpoints
    s3.endpoint: https://s3.us-east-1.amazonaws.com
    s3.path.style.access: "false"
  serviceAccount: flink
  jobManager:
    resource:
      memory: "512m" # 1024m에서 512m 으로 바꿀까? 고민중
      cpu: 0.5
  taskManager:
    resource:
      memory: "512m" # 1024m에서 512m 으로 바꿀까? 고민중
      cpu: 0.5
  podTemplate:
    spec:
      containers:
        - name: flink-main-container
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: access-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: secret-access-key
            - name: AWS_DEFAULT_REGION
              value: "us-east-1"
            - name: ENABLE_BUILT_IN_PLUGINS
              value: "flink-s3-fs-hadoop-1.18.1.jar"
  job:
    jarURI: local:///opt/flink/usrlib/flink-job-1.0-SNAPSHOT.jar
    parallelism: 1
    upgradeMode: stateless