---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: aws-credentials
  namespace: data-pipeline
spec:
  encryptedData:
    access-key-id: AgBfipPTInqU1xcQcl0jF53T+tUlqR1lmZAMDQRCoo9a8nKynt7eIukrCq22EVt8XPIRLPNEnZoqMF8ebYMVsJHJycRhfenfs0gAji4lDLGlBcJPzpwvhQm+c3t26ltgaI4K/yNkBLkI2v8bcXovVHvbyvWrxSE9lqZMDFy2dKT1Iwf2CzIUKDb6aVbOh982tJYslno5hw8sInbOj24/A8BHABzOe4fV04ecLHFw/SjBK2IyiD1hbkwc3iSl1xRBbVGVMaLvdSxy/CVrTuutDlP6tSzo7nFi2Z6K92EZUwl/YuvNzP4DGAmhGZybi1vnuHhoPDlLYXwJ2Iqb3/cImj8faT0bD83zFYOvVHOiBu9PP9+uMPRs7RwNDV31/E9iHoyhd69cuMeFn6WrKqDDkfb5WvW4RYiXze/SXXzKAbCI0J6TbO0TGChLQOg1SrZaxr8eiOPyViX6PCoW3axjLR74F+EHAy08BPEWuKHNvAGvp3XxIxf0mq9gBati1hAwzUusOSLV0UuDBjCWTDnsYrHz5GXgToju8O9bNmEmKPOklZUDix+lOuDcPkWXSjWiz342vQ2OgipX2lc1L+wPa8AtUX+TUKrKMBFf7kKA5t/69qv1coJciibW0P/5i7bC5LGPaxpbuzwQPiKPcKS5LnKM9sRphfrSBarGNahdjJVQf3NCFLm1uaOoHjSrR5rBvgo+oVxq4HvAN7rI7wRikBcyG3c0Ew==
    secret-access-key: AgCuOLaHPPKK9n6Y38NAmGvIa+zzc5uao0E4eVZ/hBdTesbSMqnassQT69xFCMuhIz16XmOEggtxFUwpUa+5xmAzSjg+oNXQRAcW8T1GD6GzMShO4HS/ndRygM+32CroAzWArYIOrRvyifmUFWpCOuUE+D+ut7v7A1+EBdwEOCmjRv3ln+pLIrlmKXJGrO9/XzDbooXIHvPppQqilOYFg4KMzik9y9BJzld9/gebptA1M7Dz9mfIoOZY09E7gV7bBIWSsgQzR9X6OQaTS1rl7hhN4iiCq3RfnPuIfso+eqac54Zn3cewX9b0Gd3K5zedmfr9YU+Jrxlb/eu9SbGwIrZmFCGN2DDByd2YvwD7SJED6kJBj0MM5dhH6rSBEAQFKH4u4+UX5daloVr2Yobt+bP0J+g5QgssdR8DsOFvSpf6u8UOpx8B2Q0CiGkdVQMlnbB2UjghvZPoTp/tpwwq/adsN8boZqSk5LFmI445/jp7RQmszGxzbbt/3AIPIkb2AEI/AvfCjbcirldVciaaodZG/Njipz11EZsSuSsR6IcWmyuXpLvOndZFkUmL4fe1nytSmG6M3hZM5C+tINLh1kXnbTPO+SvaMnk4mhtf3RgLKPX157en+EKJY5/omX2bKDK6dsQHpomccDLL6WPCWXOV4Fk7nAAsiFz1JQSW6EIsEyiz++FWegiSsfw91bvFajQxmMP5PiXBlL04cf4dMskGV25VCt3w5zPE4i60VmTcbsDRMi/ufmIS
  template:
    metadata:
      name: aws-credentials
      namespace: data-pipeline
    type: Opaque
