apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: orderflow-producer
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/w1024ji/orderflow.git
    targetRevision: main
    path: deploy/k8s/producer
  destination:
    server: https://kubernetes.default.svc
    namespace: data-pipeline
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false