apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderflow-producer
  namespace: data-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderflow-producer
  template:
    metadata:
      labels:
        app: orderflow-producer
    spec:
      containers:
        - name: producer
          image: ghcr.io/w1024ji/orderflow-producer:latest
          imagePullPolicy: Always
          env:
            - name: PYTHONUNBUFFERED
              value: "1"